# -*- coding: utf-8 -*-
"""Recuperación Recursión.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Qe0OWyQXl6m8903Mj15koYtRpivl6vTp

E1. Defina una función recursiva para determinar la cantidad de elementos en una lista L.
"""

def elementos_en_una_lista(l):
  if len(l) == 0:
    return 0
  else:
    return elementos_en_una_lista(l[:-1])+1


o = [1, 2, 3, 4, 5, 10]
elementos_en_una_lista(o)

"""E2. Defina una función recursiva que reciba una lista para determinar cuántos números pares hay en ella"""

def pares_en_una_lista(l):
  if len(l) == 0:
    return 0
  else:
    if l[-1] % 2 == 0:
      return pares_en_una_lista(l[:-1])+1
    else:
      return pares_en_una_lista(l[:-1])

p = [2, 4, 6, 7, 8, 10, 3]
pares_en_una_lista(p)

"""E3. Defina una función recursiva que reciba un nombre(str) en minúsculas y que lo devuelva con las vocales en mayúsculas"""

def min_a_may(s, k = ""):
  j = "aeiou"
  if s is not None:
    for m in s:
      if m in j:
        t = m.upper()
        k += t
        return min_a_may(s[1:], k)
      else:
        k += m
        return min_a_may(s[1:], k)
    return k

i = "juan"
min_a_may(i)

"""E4. Escriba una función recursiva que imprima los número desde un número n hasta otro número m descendentemente"""

def imprimir_descendente(n, m):
  l = []
  if n and m is not None:
    for i in range(n, m+1):
      l.append(i)
    return l[::-1]

imprimir_descendente(4, 8)

"""E5. Escriba una función recursiva que sume los digitos de un numero dado"""

def suma_digitos(n):
  if n == 0:
    return 0
  else:
    return suma_digitos(n // 10) + n % 10

suma_digitos(5163)

"""E6. Escriba una función recursiva que encuentre el mínimo de una lista L dada"""

def min(l):
  if len(l) == 0:
    return 0
  elif len(l) == 1:
    return l[0]
  else:
    m = min(l[1:])
    if m < l[0]:
      return m
    else:
      return l[0]

min([6, 3, 8, 9, 1])

"""E7. Escriba una función recursiva que invierta un string dado"""

def invertir_string(s): 
  if len(s) == 0: 
    return s 
  else: 
    return invertir_string(s[1:]) + s[0]

invertir_string("hola")

"""E8. Escribir un función recursiva para determinar si un número es primo o no"""

def es_primo(num, n=2):
  if n >= num:
    print("Es primo")
    return True
  elif num % n != 0:
    return es_primo(num, n + 1)
  else:
    print("No es primo", n, "es divisor")
    return False

es_primo(761114)