# -*- coding: utf-8 -*-
"""Reto recuperación recursión.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1zferEoeWLbtWnL0CjMkxwgSMOi6JOoKH
"""

def get_sum(l, c):
  for j in combinacionesPosibles(l):
    if sum(j) == c:
      print(j)

def combinacionesPosibles(c):
  if (len(c) == 0):
    return [[]]
  else:
    temp = combinacionesPosibles(c[:-1])
    return temp + [lc + [c[-1]] for lc in temp] 

a = [1, 2, 3, 4, 5, 6, 7, 8, 9]
get_sum(a, 10)

